### ISSUE TITLE
Debugging failed

### ISSUE THREAD

**Issue by GenaWang** [hudl/HudlDistortionCorrectionTool#2]
Hi, sorry to bother.
I was trying to reproduce this experiment in the windows environment by Cmake. But when I debugged the program on the VS2013, it showed some errors. 
Like, 1、Undefined identifier: "LINE_AA", "FILLED".  2、"FILLED" is not the number  of "cv", and "LINE_AA" is not the number of "cv".
The version of my OpenCV is 2.4.13. Is the version too old or other problems. Could you give me some help. Thanks very much.

**Comment by abuzaina** [comment]
@GenaWang  Please use OpenCV 3.1 and higher.
